import Hero from '@/components/section/Index/Hero'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Mattui-kit</title>
        <meta name="description" content="mattui-kit a simple and easyway to use react component with react | Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <Hero/>
      </main>
    </>
  )
}
